DROP DATABASE IF EXISTS Raylib;
CREATE DATABASE Raylib;
USE Raylib;

CREATE TABLE User(
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Ip VARCHAR(50),
    Pseudo VARCHAR(50) NOT NULL,
    MotDePasse VARCHAR(50) NOT NULL,
    isConnected BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE Friend(
	User_Id INTEGER NOT NULL,
	Friend_Id INTEGER NOT NULL,
	
	CONSTRAINT FK_User_Id
   FOREIGN KEY (User_Id)
   REFERENCES User(Id),

	CONSTRAINT FK_Friend_Id
   FOREIGN KEY (Friend_Id)
   REFERENCES User(Id)
);

CREATE TABLE FriendRequest(
	User_Id INTEGER NOT NULL,
	Friend_Id INTEGER NOT NULL,
	
	CONSTRAINT FK_User_Id
   FOREIGN KEY (User_Id)
   REFERENCES User(Id),

	CONSTRAINT FK_Friend_Id
   FOREIGN KEY (Friend_Id)
   REFERENCES User(Id)
);

CREATE TABLE Serveur(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	Ip VARCHAR(50) NOT NULL,
	Nom VARCHAR(50) NOT NULL,
	Nombre_Joueur INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Groupe(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	HostUser INTEGER NOT NULL
);

CREATE TABLE GroupeUser(
	Groupe_Id INTEGER NOT NULL,
	User_Id INTEGER NOT NULL,
	isReady BOOLEAN NOT NULL DEFAULT FALSE,
	
	CONSTRAINT FK_Groupe_Id
   FOREIGN KEY (Groupe_Id)
   REFERENCES Groupe(Id),
   
   CONSTRAINT FK_User_Id
   FOREIGN KEY (User_Id)
   REFERENCES User(Id)
);