DROP DATABASE IF EXISTS Raylib;
CREATE DATABASE Raylib CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE Raylib;

CREATE TABLE User (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Pseudo VARCHAR(50) NOT NULL,
    MotDePasse VARCHAR(50) NOT NULL
);

CREATE TABLE Serveur (
    Id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Ip VARCHAR(50) NOT NULL,
    Nom VARCHAR(50) NOT NULL,
    Nombre_Joueur INTEGER NOT NULL DEFAULT 0
);
